// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZdA7ZWO-4pUIf9lZj9LTtm3c6e6lv9c',
    appId: '1:886500684268:web:d1f4fec8661956c0d7d0c9',
    messagingSenderId: '886500684268',
    projectId: 'ticketing-app-9ba14',
    authDomain: 'ticketing-app-9ba14.firebaseapp.com',
    storageBucket: 'ticketing-app-9ba14.firebasestorage.app',
    measurementId: 'G-RVEDRV74V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0NHjf-TGNrbzFnSypQdWysmNT98om7a4',
    appId: '1:886500684268:android:bd091989cf450013d7d0c9',
    messagingSenderId: '886500684268',
    projectId: 'ticketing-app-9ba14',
    storageBucket: 'ticketing-app-9ba14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq9MWh9XUAYpUs4jLH2HlrTHhFexRYomo',
    appId: '1:886500684268:ios:22dc52eeee28345ed7d0c9',
    messagingSenderId: '886500684268',
    projectId: 'ticketing-app-9ba14',
    storageBucket: 'ticketing-app-9ba14.firebasestorage.app',
    iosBundleId: 'com.example.ticketingApp',
  );
}
